### ISSUE TITLE
Ghost bookmarks on the timeline

### ISSUE THREAD

**Issue by Rodeoclash** [Rodeoclash/vodon-pro#10]
Currently, bookmarks are only visible when viewing a particular video (i.e. the video that the bookmarks belong to).

One solution to this is to show "ghost" bookmarks on the global time control. Videos that have bookmarks but aren't the video being shown will start have a bookmark icon on the timeline, just "ghosted" out (i.e. 50% opacity) that indicate a bookmark is present but not currently being viewed.

Also to think about

1. This doesn't solve the issue of a lot of bookmarks being used and crowding out the timeline (Kilk had this problem). We might want to think about reducing the size of the bookmarks or lifting them off the timeline in some way to solve this. However, it does solve the issue of having a moment you want to talk about which is attached to another video.

2. How will this play if we have other items on the timeline (i.e. deaths)

**Comment by Zimurlen** [comment]
Having a skip forward and skip backward bookmark button to the left and right of bookmark we can pass through sections that have a lot of bookmarks. Though I believe having the bookmarks raised just above the timeline would help when you are scrolling through the vod but not looking to hit an exact bookmark.

**Comment by Rodeoclash** [comment]
First part of this has been implemented. I'll leave the ticket here to also tackle skipping forward / back on bookmarks.
