### ISSUE TITLE
No image, sound only when playing HEVC coded video

### ISSUE THREAD

**Issue by aw0o** [Rodeoclash/vodon-pro#51]
System: Win10 & MacOS(arm64)
Version: 1.9.4
Issue: Sound only but no image shown. 
codec information: 
![image](https://user-images.githubusercontent.com/56579560/186884301-b9069fa7-8b9f-429f-acb0-8f1d9e0e2165.png)
Playing Screenshot: 
![image](https://user-images.githubusercontent.com/56579560/186883187-767ba872-56e7-4f9e-bf29-164c6953f67b.png)
Tried to put FFMPEG64.DLL in the installation folder, doesn't help.

**Comment by Rodeoclash** [comment]
Thanks for the report.

So Vodon Pro uses Electron and Electron is powered by Google Chrome. Unfortunately it looks like Chrome doesn't support the codec (https://caniuse.com/hevc) so it won't play in Vodon Pro.

I do have plans to rebuild the app in Rust with GStreamer powering the video processing in it. That combination would support H.265. I'm waiting to see how popular the app is before I invest in porting it over to a new language though.

If you have access to FFMPEG it should be reasonably straight forward to convert the video to H.264 with an MKV container, FFMPEG as quite a good guide available on this: https://trac.ffmpeg.org/wiki/Encode/H.264

Something like: `ffmpeg -i input -c:v libx264 -preset slow -crf 22 -c:a copy output.mkv` should give fairly good results. You will lose some quality transcoding the video again however.

**Comment by aw0o** [comment]
> Thanks for the report.
> 
> So Vodon Pro uses Electron and Electron is powered by Google Chrome. Unfortunately it looks like Chrome doesn't support the codec (https://caniuse.com/hevc) so it won't play in Vodon Pro.
> 
> I do have plans to rebuild the app in Rust with GStreamer powering the video processing in it. That combination would support H.265. I'm waiting to see how popular the app is before I invest in porting it over to a new language though.
> 
> If you have access to FFMPEG it should be reasonably straight forward to convert the video to H.264 with an MKV container, FFMPEG as quite a good guide available on this: https://trac.ffmpeg.org/wiki/Encode/H.264
> 
> Something like: `ffmpeg -i input -c:v libx264 -preset slow -crf 22 -c:a copy output.mkv` should give fairly good results. You will lose some quality transcoding the video again however.

Got it, thanks!

**Comment by Rodeoclash** [comment]
I'm going to close this ticket as a can't fix for the current version, however I've included a link to it in a project around creating a Vodon Pro 2 as one of the reasons to create it 🙂 

https://github.com/users/Rodeoclash/projects/1
