### ISSUE TITLE
Start maximized

### ISSUE THREAD

**Issue by lars-vc** [Rodeoclash/vodon-pro#58]
## Idea
The application doesn't start in full-screen, it leaves gaps around the outside. I think it would make more sense to start maximized or to make the startup view smaller (like discord does), but maximized seems more logical for the use case of the app.
![image](https://user-images.githubusercontent.com/57136208/188375281-30574d5a-13e9-4644-9015-7bf1f6973cf7.png)

**Comment by Rodeoclash** [comment]
I think the gaps you're seeing here are to do with the aspect ratio of the video not quite fitting the boundary of the window containing it.

That said, I'm going to look at removing the title bar of the window and moving the dropdown menus (file being the main one I use) into the UI of the app itself. That would free up and extra ~80px of space at the top of the screen and mean that the video will expand a bit more to the edges of the screen.

**Comment by Rodeoclash** [comment]
Ahh, I see this is also tracked in https://github.com/Rodeoclash/vodon-pro/issues/59

I'll leave this ticket here though to make the app automatically start maximised.
