### ISSUE TITLE
Feature Request: Speed Increase to a Maximum of 6x Speed

### ISSUE THREAD

**Issue by MightyMar** [Rodeoclash/vodon-pro#66]
I do a lot of coaching for fighting games and I do VOD review seasons currently using video speed controller/youtube/discord. 

During my VOD reviews I frequently change speeds very high to get through downtime and catch nuances in gameplay that are difficult to catch in normal speed. 

The last VOD review site that I tried was Flowfeedback, but that one didn't go passed 2x speed so I'm making a request to go to about 6X speed at maximum. 

Thank you so much for making this tool as it will help me with coaching a lot of players!

**Comment by Rodeoclash** [comment]
No problem, I've added 4x 6x and 8x speed controls in https://github.com/Rodeoclash/vodon-pro/commit/26c204ace3e725f9001c9679f0c1efe63e22813d

I should be able to cut a release a bit later today 🙂
